# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = com.mistaboom.essence_ascendance
archives_name = essence_ascendance
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.11
fabric_loader_version = 0.19.3
fabric_api_version = 0.116.15+1.21.1
neoforge_version = 21.1.248

# Optional JEI compile-time API integration
jei_version = 19.43.0.395
