package com.mistaboom.essence_ascendance.balance.engine;

/** Dimensions retain their physical meaning; a binary capability is never treated as bonus DPS. */
public enum CapabilityAxis {
    SUSTAINED_DAMAGE, BURST_DAMAGE, AREA_DAMAGE, ATTACK_RATE, RANGE, DELIVERY_RELIABILITY,
    ARMOR_PENETRATION, SHIELD_INTERACTION, CROWD_CONTROL, DAMAGE_OVER_TIME,
    EFFECTIVE_HEALTH, ARMOR, TOUGHNESS, DAMAGE_REDUCTION, AVOIDANCE, BLOCKING, REFLECTION,
    RECOVERY, HEALING, REGENERATION, STATUS_RESISTANCE, GROUND_SPEED, JUMP, VERTICAL_MOVEMENT,
    FALL_CONTROL, GLIDING, FLIGHT, ABILITIES_FLYING_SPEED, TELEPORTATION, MINING_SPEED, AREA_MINING, VEIN_MINING,
    HARVEST_LEVEL, CROP_YIELD, DROP_YIELD, DURABILITY, REACH, ENCHANTING_EFFICIENCY,
    ANVIL_EFFICIENCY, INVENTORY, CONVERSION, THROUGHPUT, EXPERIENCE, REPAIR,
    INFORMATION, CONVENIENCE, RESOURCE_CONSUMPTION, TOOL_VERSATILITY, AUTOMATION_INTERACTION,
    BURST_SURVIVAL, SUSTAINED_SURVIVAL,
    MELEE_DAMAGE, RANGED_DAMAGE, MAGIC_DAMAGE, PROJECTILE_SPEED, CRITICAL_DAMAGE,
    SHIELD_CAPACITY, MAX_HEALTH, KNOCKBACK_RESISTANCE, DAMAGE_IMMUNITY,
    DURABILITY_REDUCTION, INDESTRUCTIBILITY, ITEM_LOSS_PREVENTION,
    STEP_HEIGHT, HARVEST_SPEED, FISHING_PRODUCTIVITY, FISHING_TIME_REDUCTION,
    AUTOMATED_EXTRACTION, AUTOMATED_FARMING, AUTOMATED_FISHING, MOB_FARMING, PASSIVE_GENERATION,
    CROP_ACCELERATION, TREE_ACCELERATION, ANIMAL_ACCELERATION,
    SPAWN_SUPPRESSION, MOB_REPULSION, HAZARD_SUPPRESSION, MACHINE_ACCELERATION,
    BLOCK_ENTITY_ACCELERATION, ENTITY_ACCELERATION, LOCAL_TIME_ACCELERATION
}
