modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "essence_ascendance"
version = "${version}"
displayName = "Essence Ascendance"
authors = "MistaBoom"
description = '''
Consume vast quantities of items to ascend your character and permanently improve combat, mobility, defense, and other abilities.
'''
#logoFile = ""

[[dependencies.essence_ascendance]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.essence_ascendance]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.essence_ascendance]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "essence_ascendance.mixins.json"

[[mixins]]
config="essence_ascendance.vitality.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
