package com.mistaboom.essence_ascendance.mapping;

import net.minecraft.resources.ResourceLocation;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Historical mapping-ID -> selector migration aliases ONLY. No prices and no
 * resource-folder dependency. Keeps existing remove_defaults/replacement intent
 * working after the bundled numeric dataset has been physically deleted. */
final class LegacyDefaultSelectors {
    private static final Map<String, List<String>> ALIASES = build();
    private LegacyDefaultSelectors() { }
    static List<String> selectors(ResourceLocation id) { return ALIASES.getOrDefault(id.toString(), List.of()); }
    private static Map<String, List<String>> build() {
        Map<String, List<String>> aliases = new LinkedHashMap<>();
        for (String row : DATA.strip().split("\\R")) {
            String[] parts = row.strip().split(" ", 2);
            aliases.put(parts[0], List.of(parts[1]));
        }
        return Map.copyOf(aliases);
    }
    private static final String DATA = """
            essence_ascendance:armor/chainmail_boots minecraft:chainmail_boots
            essence_ascendance:armor/chainmail_chestplate minecraft:chainmail_chestplate
            essence_ascendance:armor/chainmail_helmet minecraft:chainmail_helmet
            essence_ascendance:armor/chainmail_leggings minecraft:chainmail_leggings
            essence_ascendance:armor/diamond_boots minecraft:diamond_boots
            essence_ascendance:armor/diamond_chestplate minecraft:diamond_chestplate
            essence_ascendance:armor/diamond_helmet minecraft:diamond_helmet
            essence_ascendance:armor/diamond_horse_armor minecraft:diamond_horse_armor
            essence_ascendance:armor/diamond_leggings minecraft:diamond_leggings
            essence_ascendance:armor/golden_boots minecraft:golden_boots
            essence_ascendance:armor/golden_chestplate minecraft:golden_chestplate
            essence_ascendance:armor/golden_helmet minecraft:golden_helmet
            essence_ascendance:armor/golden_horse_armor minecraft:golden_horse_armor
            essence_ascendance:armor/golden_leggings minecraft:golden_leggings
            essence_ascendance:armor/iron_boots minecraft:iron_boots
            essence_ascendance:armor/iron_chestplate minecraft:iron_chestplate
            essence_ascendance:armor/iron_helmet minecraft:iron_helmet
            essence_ascendance:armor/iron_horse_armor minecraft:iron_horse_armor
            essence_ascendance:armor/iron_leggings minecraft:iron_leggings
            essence_ascendance:armor/leather_boots minecraft:leather_boots
            essence_ascendance:armor/leather_chestplate minecraft:leather_chestplate
            essence_ascendance:armor/leather_helmet minecraft:leather_helmet
            essence_ascendance:armor/leather_horse_armor minecraft:leather_horse_armor
            essence_ascendance:armor/leather_leggings minecraft:leather_leggings
            essence_ascendance:armor/netherite_boots minecraft:netherite_boots
            essence_ascendance:armor/netherite_chestplate minecraft:netherite_chestplate
            essence_ascendance:armor/netherite_helmet minecraft:netherite_helmet
            essence_ascendance:armor/netherite_leggings minecraft:netherite_leggings
            essence_ascendance:armor/shield minecraft:shield
            essence_ascendance:armor/turtle_helmet minecraft:turtle_helmet
            essence_ascendance:armor/wolf_armor minecraft:wolf_armor
            essence_ascendance:brewing/blaze_powder minecraft:blaze_powder
            essence_ascendance:brewing/blaze_rod minecraft:blaze_rod
            essence_ascendance:brewing/brewing_stand minecraft:brewing_stand
            essence_ascendance:brewing/dragon_breath minecraft:dragon_breath
            essence_ascendance:brewing/fermented_spider_eye minecraft:fermented_spider_eye
            essence_ascendance:brewing/ghast_tear minecraft:ghast_tear
            essence_ascendance:brewing/glistering_melon_slice minecraft:glistering_melon_slice
            essence_ascendance:brewing/magma_cream minecraft:magma_cream
            essence_ascendance:brewing/nether_wart minecraft:nether_wart
            essence_ascendance:brewing/phantom_membrane minecraft:phantom_membrane
            essence_ascendance:brewing/pufferfish minecraft:pufferfish
            essence_ascendance:brewing/rabbit_foot minecraft:rabbit_foot
            essence_ascendance:brewing/spider_eye minecraft:spider_eye
            essence_ascendance:brewing/sugar minecraft:sugar
            essence_ascendance:enchanting/book minecraft:book
            essence_ascendance:enchanting/bookshelf minecraft:bookshelf
            essence_ascendance:enchanting/enchanted_book minecraft:enchanted_book
            essence_ascendance:enchanting/enchanting_table minecraft:enchanting_table
            essence_ascendance:enchanting/experience_bottle minecraft:experience_bottle
            essence_ascendance:enchanting/netherite_upgrade_smithing_template minecraft:netherite_upgrade_smithing_template
            essence_ascendance:food/apple minecraft:apple
            essence_ascendance:food/baked_potato minecraft:baked_potato
            essence_ascendance:food/beef minecraft:beef
            essence_ascendance:food/beetroot minecraft:beetroot
            essence_ascendance:food/beetroot_soup minecraft:beetroot_soup
            essence_ascendance:food/bread minecraft:bread
            essence_ascendance:food/cake minecraft:cake
            essence_ascendance:food/carrot minecraft:carrot
            essence_ascendance:food/chicken minecraft:chicken
            essence_ascendance:food/chorus_fruit minecraft:chorus_fruit
            essence_ascendance:food/cod minecraft:cod
            essence_ascendance:food/cooked_beef minecraft:cooked_beef
            essence_ascendance:food/cooked_chicken minecraft:cooked_chicken
            essence_ascendance:food/cooked_cod minecraft:cooked_cod
            essence_ascendance:food/cooked_mutton minecraft:cooked_mutton
            essence_ascendance:food/cooked_porkchop minecraft:cooked_porkchop
            essence_ascendance:food/cooked_rabbit minecraft:cooked_rabbit
            essence_ascendance:food/cooked_salmon minecraft:cooked_salmon
            essence_ascendance:food/cookie minecraft:cookie
            essence_ascendance:food/dried_kelp minecraft:dried_kelp
            essence_ascendance:food/enchanted_golden_apple minecraft:enchanted_golden_apple
            essence_ascendance:food/glow_berries minecraft:glow_berries
            essence_ascendance:food/golden_apple minecraft:golden_apple
            essence_ascendance:food/golden_carrot minecraft:golden_carrot
            essence_ascendance:food/honey_bottle minecraft:honey_bottle
            essence_ascendance:food/melon_slice minecraft:melon_slice
            essence_ascendance:food/mushroom_stew minecraft:mushroom_stew
            essence_ascendance:food/mutton minecraft:mutton
            essence_ascendance:food/porkchop minecraft:porkchop
            essence_ascendance:food/potato minecraft:potato
            essence_ascendance:food/pumpkin_pie minecraft:pumpkin_pie
            essence_ascendance:food/rabbit minecraft:rabbit
            essence_ascendance:food/rabbit_stew minecraft:rabbit_stew
            essence_ascendance:food/salmon minecraft:salmon
            essence_ascendance:food/suspicious_stew minecraft:suspicious_stew
            essence_ascendance:food/sweet_berries minecraft:sweet_berries
            essence_ascendance:food/tropical_fish minecraft:tropical_fish
            essence_ascendance:miscellaneous/armadillo_scute minecraft:armadillo_scute
            essence_ascendance:miscellaneous/bone minecraft:bone
            essence_ascendance:miscellaneous/breeze_rod minecraft:breeze_rod
            essence_ascendance:miscellaneous/feather minecraft:feather
            essence_ascendance:miscellaneous/gunpowder minecraft:gunpowder
            essence_ascendance:miscellaneous/heart_of_the_sea minecraft:heart_of_the_sea
            essence_ascendance:miscellaneous/heavy_core minecraft:heavy_core
            essence_ascendance:miscellaneous/honeycomb minecraft:honeycomb
            essence_ascendance:miscellaneous/leather minecraft:leather
            essence_ascendance:miscellaneous/nautilus_shell minecraft:nautilus_shell
            essence_ascendance:miscellaneous/nether_star minecraft:nether_star
            essence_ascendance:miscellaneous/ominous_bottle minecraft:ominous_bottle
            essence_ascendance:miscellaneous/ominous_trial_key minecraft:ominous_trial_key
            essence_ascendance:miscellaneous/rabbit_hide minecraft:rabbit_hide
            essence_ascendance:miscellaneous/shulker_shell minecraft:shulker_shell
            essence_ascendance:miscellaneous/slime_ball minecraft:slime_ball
            essence_ascendance:miscellaneous/string minecraft:string
            essence_ascendance:miscellaneous/totem_of_undying minecraft:totem_of_undying
            essence_ascendance:miscellaneous/trial_key minecraft:trial_key
            essence_ascendance:miscellaneous/turtle_scute minecraft:turtle_scute
            essence_ascendance:miscellaneous/wither_skeleton_skull minecraft:wither_skeleton_skull
            essence_ascendance:movement/activator_rail minecraft:activator_rail
            essence_ascendance:movement/boats #minecraft:boats
            essence_ascendance:movement/carrot_on_a_stick minecraft:carrot_on_a_stick
            essence_ascendance:movement/chest_boats #minecraft:chest_boats
            essence_ascendance:movement/chest_minecart minecraft:chest_minecart
            essence_ascendance:movement/compass minecraft:compass
            essence_ascendance:movement/detector_rail minecraft:detector_rail
            essence_ascendance:movement/elytra minecraft:elytra
            essence_ascendance:movement/ender_eye minecraft:ender_eye
            essence_ascendance:movement/ender_pearl minecraft:ender_pearl
            essence_ascendance:movement/filled_map minecraft:filled_map
            essence_ascendance:movement/furnace_minecart minecraft:furnace_minecart
            essence_ascendance:movement/hopper_minecart minecraft:hopper_minecart
            essence_ascendance:movement/map minecraft:map
            essence_ascendance:movement/minecart minecraft:minecart
            essence_ascendance:movement/powered_rail minecraft:powered_rail
            essence_ascendance:movement/rail minecraft:rail
            essence_ascendance:movement/recovery_compass minecraft:recovery_compass
            essence_ascendance:movement/saddle minecraft:saddle
            essence_ascendance:movement/tnt_minecart minecraft:tnt_minecart
            essence_ascendance:movement/warped_fungus_on_a_stick minecraft:warped_fungus_on_a_stick
            essence_ascendance:movement/wind_charge minecraft:wind_charge
            essence_ascendance:redstone/comparator minecraft:comparator
            essence_ascendance:redstone/copper_bulb minecraft:copper_bulb
            essence_ascendance:redstone/crafter minecraft:crafter
            essence_ascendance:redstone/daylight_detector minecraft:daylight_detector
            essence_ascendance:redstone/dispenser minecraft:dispenser
            essence_ascendance:redstone/dropper minecraft:dropper
            essence_ascendance:redstone/exposed_copper_bulb minecraft:exposed_copper_bulb
            essence_ascendance:redstone/hopper minecraft:hopper
            essence_ascendance:redstone/lightning_rod minecraft:lightning_rod
            essence_ascendance:redstone/observer minecraft:observer
            essence_ascendance:redstone/oxidized_copper_bulb minecraft:oxidized_copper_bulb
            essence_ascendance:redstone/piston minecraft:piston
            essence_ascendance:redstone/redstone_lamp minecraft:redstone_lamp
            essence_ascendance:redstone/redstone_torch minecraft:redstone_torch
            essence_ascendance:redstone/repeater minecraft:repeater
            essence_ascendance:redstone/sticky_piston minecraft:sticky_piston
            essence_ascendance:redstone/target minecraft:target
            essence_ascendance:redstone/tripwire_hook minecraft:tripwire_hook
            essence_ascendance:redstone/waxed_copper_bulb minecraft:waxed_copper_bulb
            essence_ascendance:redstone/waxed_exposed_copper_bulb minecraft:waxed_exposed_copper_bulb
            essence_ascendance:redstone/waxed_oxidized_copper_bulb minecraft:waxed_oxidized_copper_bulb
            essence_ascendance:redstone/waxed_weathered_copper_bulb minecraft:waxed_weathered_copper_bulb
            essence_ascendance:redstone/weathered_copper_bulb minecraft:weathered_copper_bulb
            essence_ascendance:resources/amethyst_shard minecraft:amethyst_shard
            essence_ascendance:resources/ancient_debris minecraft:ancient_debris
            essence_ascendance:resources/coal_block minecraft:coal_block
            essence_ascendance:resources/coal_ores #minecraft:coal_ores
            essence_ascendance:resources/coals #minecraft:coals
            essence_ascendance:resources/copper_block minecraft:copper_block
            essence_ascendance:resources/copper_ingot minecraft:copper_ingot
            essence_ascendance:resources/copper_ores #minecraft:copper_ores
            essence_ascendance:resources/crying_obsidian minecraft:crying_obsidian
            essence_ascendance:resources/deepslate_gold_ore minecraft:deepslate_gold_ore
            essence_ascendance:resources/diamond minecraft:diamond
            essence_ascendance:resources/diamond_block minecraft:diamond_block
            essence_ascendance:resources/diamond_ores #minecraft:diamond_ores
            essence_ascendance:resources/echo_shard minecraft:echo_shard
            essence_ascendance:resources/emerald minecraft:emerald
            essence_ascendance:resources/emerald_block minecraft:emerald_block
            essence_ascendance:resources/emerald_ores #minecraft:emerald_ores
            essence_ascendance:resources/flint minecraft:flint
            essence_ascendance:resources/glowstone minecraft:glowstone
            essence_ascendance:resources/glowstone_dust minecraft:glowstone_dust
            essence_ascendance:resources/gold_block minecraft:gold_block
            essence_ascendance:resources/gold_ingot minecraft:gold_ingot
            essence_ascendance:resources/gold_nugget minecraft:gold_nugget
            essence_ascendance:resources/gold_ore minecraft:gold_ore
            essence_ascendance:resources/honey_block minecraft:honey_block
            essence_ascendance:resources/iron_block minecraft:iron_block
            essence_ascendance:resources/iron_ingot minecraft:iron_ingot
            essence_ascendance:resources/iron_nugget minecraft:iron_nugget
            essence_ascendance:resources/iron_ores #minecraft:iron_ores
            essence_ascendance:resources/lapis_block minecraft:lapis_block
            essence_ascendance:resources/lapis_lazuli minecraft:lapis_lazuli
            essence_ascendance:resources/lapis_ores #minecraft:lapis_ores
            essence_ascendance:resources/nether_gold_ore minecraft:nether_gold_ore
            essence_ascendance:resources/nether_quartz_ore minecraft:nether_quartz_ore
            essence_ascendance:resources/netherite_block minecraft:netherite_block
            essence_ascendance:resources/netherite_ingot minecraft:netherite_ingot
            essence_ascendance:resources/netherite_scrap minecraft:netherite_scrap
            essence_ascendance:resources/obsidian minecraft:obsidian
            essence_ascendance:resources/prismarine_crystals minecraft:prismarine_crystals
            essence_ascendance:resources/prismarine_shard minecraft:prismarine_shard
            essence_ascendance:resources/quartz minecraft:quartz
            essence_ascendance:resources/raw_copper minecraft:raw_copper
            essence_ascendance:resources/raw_copper_block minecraft:raw_copper_block
            essence_ascendance:resources/raw_gold minecraft:raw_gold
            essence_ascendance:resources/raw_gold_block minecraft:raw_gold_block
            essence_ascendance:resources/raw_iron minecraft:raw_iron
            essence_ascendance:resources/raw_iron_block minecraft:raw_iron_block
            essence_ascendance:resources/redstone minecraft:redstone
            essence_ascendance:resources/redstone_block minecraft:redstone_block
            essence_ascendance:resources/redstone_ores #minecraft:redstone_ores
            essence_ascendance:resources/sea_lantern minecraft:sea_lantern
            essence_ascendance:resources/slime_block minecraft:slime_block
            essence_ascendance:tools/brush minecraft:brush
            essence_ascendance:tools/diamond_axe minecraft:diamond_axe
            essence_ascendance:tools/diamond_hoe minecraft:diamond_hoe
            essence_ascendance:tools/diamond_pickaxe minecraft:diamond_pickaxe
            essence_ascendance:tools/diamond_shovel minecraft:diamond_shovel
            essence_ascendance:tools/fishing_rod minecraft:fishing_rod
            essence_ascendance:tools/flint_and_steel minecraft:flint_and_steel
            essence_ascendance:tools/golden_axe minecraft:golden_axe
            essence_ascendance:tools/golden_hoe minecraft:golden_hoe
            essence_ascendance:tools/golden_pickaxe minecraft:golden_pickaxe
            essence_ascendance:tools/golden_shovel minecraft:golden_shovel
            essence_ascendance:tools/iron_axe minecraft:iron_axe
            essence_ascendance:tools/iron_hoe minecraft:iron_hoe
            essence_ascendance:tools/iron_pickaxe minecraft:iron_pickaxe
            essence_ascendance:tools/iron_shovel minecraft:iron_shovel
            essence_ascendance:tools/netherite_axe minecraft:netherite_axe
            essence_ascendance:tools/netherite_hoe minecraft:netherite_hoe
            essence_ascendance:tools/netherite_pickaxe minecraft:netherite_pickaxe
            essence_ascendance:tools/netherite_shovel minecraft:netherite_shovel
            essence_ascendance:tools/shears minecraft:shears
            essence_ascendance:tools/stone_axe minecraft:stone_axe
            essence_ascendance:tools/stone_hoe minecraft:stone_hoe
            essence_ascendance:tools/stone_pickaxe minecraft:stone_pickaxe
            essence_ascendance:tools/stone_shovel minecraft:stone_shovel
            essence_ascendance:tools/wooden_axe minecraft:wooden_axe
            essence_ascendance:tools/wooden_hoe minecraft:wooden_hoe
            essence_ascendance:tools/wooden_pickaxe minecraft:wooden_pickaxe
            essence_ascendance:tools/wooden_shovel minecraft:wooden_shovel
            essence_ascendance:utility/anvil minecraft:anvil
            essence_ascendance:utility/axolotl_bucket minecraft:axolotl_bucket
            essence_ascendance:utility/barrel minecraft:barrel
            essence_ascendance:utility/beacon minecraft:beacon
            essence_ascendance:utility/beds #minecraft:beds
            essence_ascendance:utility/bee_nest minecraft:bee_nest
            essence_ascendance:utility/beehive minecraft:beehive
            essence_ascendance:utility/bell minecraft:bell
            essence_ascendance:utility/black_shulker_box minecraft:black_shulker_box
            essence_ascendance:utility/blast_furnace minecraft:blast_furnace
            essence_ascendance:utility/blue_shulker_box minecraft:blue_shulker_box
            essence_ascendance:utility/brown_shulker_box minecraft:brown_shulker_box
            essence_ascendance:utility/bucket minecraft:bucket
            essence_ascendance:utility/calibrated_sculk_sensor minecraft:calibrated_sculk_sensor
            essence_ascendance:utility/campfire minecraft:campfire
            essence_ascendance:utility/cartography_table minecraft:cartography_table
            essence_ascendance:utility/cauldron minecraft:cauldron
            essence_ascendance:utility/chest minecraft:chest
            essence_ascendance:utility/chipped_anvil minecraft:chipped_anvil
            essence_ascendance:utility/chiseled_bookshelf minecraft:chiseled_bookshelf
            essence_ascendance:utility/clock minecraft:clock
            essence_ascendance:utility/cod_bucket minecraft:cod_bucket
            essence_ascendance:utility/composter minecraft:composter
            essence_ascendance:utility/conduit minecraft:conduit
            essence_ascendance:utility/crafting_table minecraft:crafting_table
            essence_ascendance:utility/cyan_shulker_box minecraft:cyan_shulker_box
            essence_ascendance:utility/damaged_anvil minecraft:damaged_anvil
            essence_ascendance:utility/ender_chest minecraft:ender_chest
            essence_ascendance:utility/fletching_table minecraft:fletching_table
            essence_ascendance:utility/furnace minecraft:furnace
            essence_ascendance:utility/goat_horn minecraft:goat_horn
            essence_ascendance:utility/gray_shulker_box minecraft:gray_shulker_box
            essence_ascendance:utility/green_shulker_box minecraft:green_shulker_box
            essence_ascendance:utility/grindstone minecraft:grindstone
            essence_ascendance:utility/lava_bucket minecraft:lava_bucket
            essence_ascendance:utility/lead minecraft:lead
            essence_ascendance:utility/lectern minecraft:lectern
            essence_ascendance:utility/light_blue_shulker_box minecraft:light_blue_shulker_box
            essence_ascendance:utility/light_gray_shulker_box minecraft:light_gray_shulker_box
            essence_ascendance:utility/lime_shulker_box minecraft:lime_shulker_box
            essence_ascendance:utility/lodestone minecraft:lodestone
            essence_ascendance:utility/loom minecraft:loom
            essence_ascendance:utility/magenta_shulker_box minecraft:magenta_shulker_box
            essence_ascendance:utility/milk_bucket minecraft:milk_bucket
            essence_ascendance:utility/name_tag minecraft:name_tag
            essence_ascendance:utility/orange_shulker_box minecraft:orange_shulker_box
            essence_ascendance:utility/pink_shulker_box minecraft:pink_shulker_box
            essence_ascendance:utility/powder_snow_bucket minecraft:powder_snow_bucket
            essence_ascendance:utility/pufferfish_bucket minecraft:pufferfish_bucket
            essence_ascendance:utility/purple_shulker_box minecraft:purple_shulker_box
            essence_ascendance:utility/red_shulker_box minecraft:red_shulker_box
            essence_ascendance:utility/respawn_anchor minecraft:respawn_anchor
            essence_ascendance:utility/salmon_bucket minecraft:salmon_bucket
            essence_ascendance:utility/sculk_catalyst minecraft:sculk_catalyst
            essence_ascendance:utility/sculk_sensor minecraft:sculk_sensor
            essence_ascendance:utility/shulker_box minecraft:shulker_box
            essence_ascendance:utility/smithing_table minecraft:smithing_table
            essence_ascendance:utility/smoker minecraft:smoker
            essence_ascendance:utility/soul_campfire minecraft:soul_campfire
            essence_ascendance:utility/sponge minecraft:sponge
            essence_ascendance:utility/spyglass minecraft:spyglass
            essence_ascendance:utility/stonecutter minecraft:stonecutter
            essence_ascendance:utility/tadpole_bucket minecraft:tadpole_bucket
            essence_ascendance:utility/trapped_chest minecraft:trapped_chest
            essence_ascendance:utility/tropical_fish_bucket minecraft:tropical_fish_bucket
            essence_ascendance:utility/water_bucket minecraft:water_bucket
            essence_ascendance:utility/wet_sponge minecraft:wet_sponge
            essence_ascendance:utility/white_shulker_box minecraft:white_shulker_box
            essence_ascendance:utility/yellow_shulker_box minecraft:yellow_shulker_box
            essence_ascendance:weapons/arrow minecraft:arrow
            essence_ascendance:weapons/bow minecraft:bow
            essence_ascendance:weapons/crossbow minecraft:crossbow
            essence_ascendance:weapons/diamond_sword minecraft:diamond_sword
            essence_ascendance:weapons/end_crystal minecraft:end_crystal
            essence_ascendance:weapons/fire_charge minecraft:fire_charge
            essence_ascendance:weapons/golden_sword minecraft:golden_sword
            essence_ascendance:weapons/iron_sword minecraft:iron_sword
            essence_ascendance:weapons/mace minecraft:mace
            essence_ascendance:weapons/netherite_sword minecraft:netherite_sword
            essence_ascendance:weapons/spectral_arrow minecraft:spectral_arrow
            essence_ascendance:weapons/stone_sword minecraft:stone_sword
            essence_ascendance:weapons/tipped_arrow minecraft:tipped_arrow
            essence_ascendance:weapons/tnt minecraft:tnt
            essence_ascendance:weapons/trident minecraft:trident
            essence_ascendance:weapons/wooden_sword minecraft:wooden_sword
            """;
}
